mixed-port: 7890
allow-lan: false
mode: global
log-level: silent

proxies:
  - name: KDL-China
    type: socks5
    server: q360.kdltpspro.com
    port: 15818
    username: t18521305213132
    password: vrs981gj

proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - KDL-China
      - DIRECT

rules:
  - MATCH,GLOBAL
