mixed-port: 7890
allow-lan: false
mode: global
log-level: silent

proxies:
  - name: PC-Home
    type: socks5
    server: 183.161.248.96
    port: 19443
    username: forge
    password: Q3DLo_jYvBCAZkJpDCOmdQ

proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - PC-Home
      - DIRECT

rules:
  - MATCH,GLOBAL
